# Create Contoso Supermarket AI app
apiVersion: v1
kind: Service
metadata:
  name: contosoai
  namespace: contoso
  labels:
    app: contosoai
spec:
  selector:
    app: contosoai
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoai
  namespace: contoso
  labels:
    app: contosoai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosoai
  template:
    metadata:
      labels:
        app: contosoai
    spec:
      containers:
        - name: contosoai
          image: oneedgedemo.azurecr.io/contoso-supermarket/contosoai:latest
          ports:
            - containerPort: 8000
