apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pos
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: pos
  chart:
    spec:
      chart: ./operations/contoso_supermarket
  values:
    github_User: agoraedge
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "admin"
      database: "contoso"
    cosmos:
      container: "pos"
      database: "contoso"
      endpoint: https://builddemo.documents.azure.com:443/
    point_of_sale:
      title: "Contoso Supermarket 2023"
      cameras_enabled: "True"
      cameras_url: ""
      new_category: "True"
      holiday_banner: "False"
      store_id: 1
      store_location: "Seattle"
